#<% require 'kitchen-sync' %>
---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  google_client_email: <%= ENV['GOOGLE_CLIENT_EMAIL'] %>
  google_key_location: <%= ENV['GOOGLE_KEY_LOCATION'] %>
  google_project: <%= ENV['GOOGLE_PROJECT'] %>
  joyent_username: <%= ENV['SDC_CLI_ACCOUNT'] %>
  joyent_keyfile: <%= ENV['SDC_CLI_IDENTITY'] %>
  joyent_keyname: <%= ENV['SDC_CLI_KEY_ID'] %>
  joyent_url: <%= ENV['SDC_CLI_URL'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  flavor_id: <%= ENV['EC2_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.1.1

platforms:
- name: amazon-2014.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-9a6ed3f2
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: centos-5.8
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-5-8-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: centos-6.5
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-6-5-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: centos-7.0
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-7-0-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

# - name: redhat-6.5
#   driver_plugin: ec2
#   driver_config:
#     image_id: ami-8d756fe4
#     username: ec2-user
#     ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
#   run_list:
#   - recipe[selinux::disabled]

# - name: redhat-7.0
#   driver_plugin: ec2
#   driver_config:
#     image_id: ami-a8d369c0
#     username: ec2-user
#     ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
#   run_list:
#   - recipe[selinux::disabled]

- name: fedora-20
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: fedora-20-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: fedora-21
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: fedora-21-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: debian-7.0
  driver_plugin: gce
  driver_config:
    image_name: debian-7-wheezy-v20131120
    zone: <%= ENV['GCE_ZONE'] %>
    area: <%= ENV['GCE_AREA'] %>
    network: <%= ENV['GCE_NETWORK'] %>
    username: <%= ENV['GCE_USERNAME'] %>
    public_key_path: <%= ENV['GCE_PUBLIC_KEY_PATH'] %>
    ssh_key: <%= ENV['GCE_SSH_KEY_PATH'] %>
    machine_type: n1-standard-4
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-10-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-12-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-14-04-x64
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: suse-11.3
  driver_plugin: ec2
  driver_config:
    image_id: ami-e8084981
    username: root
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

# - name: omnios-151006
#   driver_plugin: ec2
#   driver_config:
#     image_id: ami-35eb835c
#     flavor_id: m3.large
#     username: root
#     ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
#   run_list:
#   - recipe[ips-omniti]

# - name: smartos-14.3.0
#   driver_plugin: joyent
#   driver_config:
#     joyent_image_id: 62f148f8-6e84-11e4-82c5-efca60348b9f
#     joyent_flavor_id: g3-standard-4-smartos
#     username: root
#     ssh_key: <%= ENV['SDC_CLI_IDENTITY'] %>
#   busser:
#     ruby_bindir: '/opt/local/bin/'
#   provisioner:
#     sudo: false
#     chef_omnibus_url: https://raw.github.com/test-kitchen/kitchen-joyent/master/scripts/install-smartos.sh

suites:
  ##############################
  # php_runtime package provider
  ##############################
  - name: runtime51-package
    run_list:
      - recipe[php_runtime_test::package]
    attributes:
      php:
       version: '5.1'
    includes: ['centos-5.8']

  - name: runtime53-package
    run_list:
      - recipe[php_runtime_test::package]
    attributes:
      php:
       version: '5.3'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'ubuntu-10.04',
      'ubuntu-12.04',
      'omnios-151006'
    ]

  - name: runtime54-package
    run_list:
      - recipe[php_runtime_test::package]
    attributes:
      php:
       version: '5.4'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'debian-7.0'
    ]

  - name: runtime55-package
    run_list:
      - recipe[php_runtime_test::package]
    attributes:
      php:
       version: '5.5'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20',
      'ubuntu-14.04'
    ]

  - name: runtime56-package
    run_list:
      - recipe[php_runtime_test::package]
    attributes:
      php:
       version: '5.6'
    includes: [
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20',
      'fedora-21',
    ]

  #############################
  # php_runtime source provider
  #############################
  # - name: runtime-source
  #   run_list:
  #     - recipe[php_runtime_test::source]
  #   includes: [
  #     'centos-5.8',
  #     'centos-6.5',
  #     'centos-7.0',
  #     'fedora-20',
  #     'fedora-21',
  #     'debian-7.0',
  #     'ubuntu-10.04',
  #     'ubuntu-12.04',
  #     'ubuntu-14.04'
  #   ]

  ##################
  # php_pear_channel
  ##################
  - name: pear-channel51
    run_list:
      - recipe[php_pear_channel_test]
    attributes:
      php:
       version: '5.1'
    includes: [ 'centos-5.8' ]

  - name: pear-channel53
    run_list:
      - recipe[php_pear_channel_test]
    attributes:
      php:
       version: '5.3'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'ubuntu-10.04',
      'ubuntu-12.04',
    ]

  - name: pear-channel54
    run_list:
      - recipe[php_pear_channel_test]
    attributes:
      php:
       version: '5.4'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'debian-7.0'
    ]

  - name: pear-channel55
    run_list:
      - recipe[php_pear_channel_test]
    attributes:
      php:
       version: '5.5'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20',
      'ubuntu-14.04'
    ]

  - name: pear-channel56
    run_list:
      - recipe[php_pear_channel_test]
    attributes:
      php:
       version: '5.6'
    includes: [
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20',
      'fedora-21',
    ]

  ##########
  # php_pear
  ##########
  - name: pear-package51
    run_list:
      - recipe[php_pear_test]
    attributes:
      php:
       version: '5.1'
    includes: [
      'centos-5.8',
    ]

  - name: pear-package53
    run_list:
      - recipe[php_pear_test]
    attributes:
      php:
       version: '5.3'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'ubuntu-10.04',
      'ubuntu-12.04',
    ]

  - name: pear-package54
    run_list:
      - recipe[php_pear_test]
    attributes:
      php:
       version: '5.4'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'debian-7.0'
    ]

  - name: pear-package55
    run_list:
      - recipe[php_pear_test]
    attributes:
      php:
       version: '5.5'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20',
      'ubuntu-14.04'
    ]

  - name: pear-package56
    run_list:
      - recipe[php_pear_test]
    attributes:
      php:
       version: '5.6'
    includes: [
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20',
      'fedora-21',
    ]

  ############
  # php_module
  ############
  - name: module51
    run_list:
      - recipe[php_module_test]
    attributes:
      php:
       version: '5.1'
    includes: [
      'centos-5.8',
    ]

  - name: module53
    run_list:
      - recipe[php_module_test]
    attributes:
      php:
       version: '5.3'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'ubuntu-10.04',
      'ubuntu-12.04',
    ]

  - name: module54
    run_list:
      - recipe[php_module_test]
    attributes:
      php:
       version: '5.4'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'debian-7.0'
    ]

  - name: module55
    run_list:
      - recipe[php_module_test]
    attributes:
      php:
       version: '5.5'
    includes: [
      'amazon-2014.09',
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20',
      'ubuntu-14.04'
    ]

  - name: module56
    run_list:
      - recipe[php_module_test]
    attributes:
      php:
       version: '5.6'
    includes: [
      'centos-5.8',
      'centos-6.5',
      'centos-7.0',
      'fedora-20',
      'fedora-21',
    ]